### ISSUE TITLE
*.map files checked in?

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-genericfilter#6]
Should we check in `*.map`? I'd personally call for a No. 

Cc @beroes @davidyezsetz.

**Comment by davidyezsetz** [comment]
Definitely no. We don't check in any generated files

**Comment by GeorgMeyer23** [comment]
will remove *.map
We check in at least min.js to provide a better accessibility.

**Comment by ain** [comment]
:+1:
